name: Compile Android Self
on: [push]
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "en_EN.UTF-8"

jobs:
  compile-android-self:
    runs-on: [self-hosted, Linux]
    steps:
    - name: checkout sources
      uses: actions/checkout@master

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         # GraalVM version. Default: latest
         graalvm: 'latest'
         # Java version. Since GraalVM 22, either java11, java17 or java23. Before GraalVM 22, empty. Default: java23
         jdk: 'java23'
         # Architecture flag. Available options are 'x86_64' (default) and 'aarch64'. The latter is available for M1 runners starting GraalVM 22.1.
         arch: 'x86_64'

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      
#    - name: Install missing packages
#      run: sudo apt-get install libgtk-3-dev libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev
      
    - name: Compile
      run:  locale ; mvn -U -s settings.xml -Pandroid clean gluonfx:compile

    - name: Link
      run:  mvn -Pandroid -s settings.xml gluonfx:link
        
    - name: Show result
      run: ls target/gluonfx

    - name: Package
      run:  mvn -Pandroid -s settings.xml gluonfx:package
        
    - name: Show result
      run: find target/gluonfx
        
    - name: Show result
      run: |
         ls target/gluonfx/aarch64-android/gvm 
         find target/gluonfx/aarch64-android/
#         cat target/gluonfx/aarch64-android/gensrc/android/AndroidManifest.xml
#         zip -r android-gensrc.zip target/gluonfx/aarch64-android/gensrc/android

#    - name: Upload Generated sources
#      uses: actions/upload-artifact@v1
#      with:
#        name: android-gensrc.zip
#        path: android-gensrc.zip
        
    - name: Prepare staging
      run: |
        mkdir staging 
        cp target/gluonfx/aarch64-android/gvm/CommLink6.apk staging/Commlink6-${{ env.RELEASE_VERSION }}.apk
#        cp target/gluonfx/aarch64-android/gvm/CommLink6.aab staging/Commlink6-${{ env.RELEASE_VERSION }}.aab

#    - name: Upload APK
#      uses: actions/upload-artifact@v1
#      with:
#        name: CommLink6-de-${{ env.RELEASE_VERSION }}.apk
#        path: target/gluonfx/aarch64-android/gvm/CommLink6.apk

#    - name: Upload APK
#      uses: actions/upload-artifact@v1
#      with:
#        name: CommLink6-de-${{ env.RELEASE_VERSION }}.aab
#        path: target/gluonfx/aarch64-android/gvm/CommLink6.aab
      
    - name: Upload 
      continue-on-error: true
      uses: appleboy/scp-action@master
      with:
        source: staging/*
        target: /var/www/html/commlink6-builds/android
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}
      
      