name: Compile Linux
on: [push]
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  GRAALVM_VERSION: "21.0.0"
  JAVA_VERSION: "java11"
  LANG: "de_DE.UTF-8"

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
 
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    

    - name: setup-graalvm-ce
      uses: rinx/setup-graalvm-ce@v0.0.4
      with:
          graalvm-version: "21.0.0"
          java-version: "java11"
          native-image: "true"

    - name: Compile
      run:  export LC_ALL=de_DE.UTF-8; export LC_MESSAGES=de_DE.UTF-8; locale ; mvn -U -s settings.xml clean client:compile
      env: 
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        LANG: de_DE
      
    - name: Install missing packages
      run: sudo apt-get install libgtk-3-dev libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev

    - name: Link
      run:  mvn client:link
        
    - name: Show result
      run: ls target/client/x86_64-linux

    - name: Logs
      if: always()      
      run: cat target/client/x86_64-linux/gvm/log/client-debug0.log

    - name: Upload Linux binary
      uses: actions/upload-artifact@v1
      with:
        name: KommLink-Linux
        path: target/client/x86_64-linux/KommLink

#    - name: Upload 
#      uses: appleboy/scp-action@master
#      with:
#        host: euve265084.serverprofi24.de
#        username: bitbucket
#        password: Oop6oi1o
#        source: "target/client/x86_64-linux/Mondtor"
#        target: "/var/www/html/downloads/linux"
#        strip_components: 3
      
  compile-android:
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v1
      
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    

    - name: setup-graalvm-ce
      uses: rinx/setup-graalvm-ce@v0.0.4
      with:
          graalvm-version: "20.2.0"
          java-version: "java11"
          native-image: "true"
      
    - name: Install missing packages
      run: sudo apt-get install libgtk-3-dev libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev
      
    - name: Compile
      run:  locale ; mvn -U -s settings.xml clean client:compile  -Pandroid
      env:
        LANG: "de_DE.UTF-8"

    - name: Link
      run:  mvn client:link -Pandroid
        
    - name: Show result
      run: ls target/client

    - name: Package
      run:  mvn client:package -Pandroid
        
    - name: Show result
      run: |
         ls target/client/aarch64-android/gvm 
         find target/client/aarch64-android/gensrc/android 
         cat target/client/aarch64-android/gensrc/android/AndroidManifest.xml
         zip -r android-gensrc.zip target/client/aarch64-android/gensrc/android

    - name: Upload Generated sources
      uses: actions/upload-artifact@v1
      with:
        name: android-gensrc.zip
        path: android-gensrc.zip

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: KommLink.apk
        path: target/client/aarch64-android/gvm/KommLink.apk
        
#    - name: Upload
#      uses: appleboy/scp-action@master
#      with:
#        host: euve265084.serverprofi24.de
#        username: bitbucket
#        password: Oop6oi1o
#        source: "target/client/aarch64-android/gvm/*.apk"
#        target: "/var/www/html/downloads/linux"
#        strip_components: 4
      
      