name: Compile Linux
on: [push]
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "de_DE.UTF-8"

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
 
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # GraalVM version. Default: latest
        graalvm: '22.0.0.3-Final'
        # Java version. Since GraalVM 22, either java11 or java17, before GraalVM 22, empty. Default: java17
        jdk: 'java17'

    - name: Compile
      run:  export LC_ALL=de_DE.UTF-8; export LC_MESSAGES=de_DE.UTF-8; locale ; mvn -U -s settings.xml clean gluonfx:compile
      env: 
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        LANG: de_DE
      
    - name: Install missing packages
      run: sudo apt-get install libgtk-3-dev libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev

    - name: Link
      run:  mvn gluonfx:link
        
    - name: Show result
      run: ls target/gluonfx

    - name: Package
      run:  mvn gluonfx:package
        
    - name: Show result
      run: ls target/gluonfx/x86_64-linux

    - name: Logs
      if: always()      
      run: cat target/gluonfx/x86_64-linux/gvm/log/client-debug0.log

    - name: Upload Linux binary
      uses: actions/upload-artifact@v1
      with:
        name: ComLink6-Linux
        path: target/gluonfx/x86_64-linux/ComLink6

#    - name: Upload 
#      uses: appleboy/scp-action@master
#      with:
#        host: euve265084.serverprofi24.de
#        username: bitbucket
#        password: Oop6oi1o
#        source: "target/client/x86_64-linux/Mondtor"
#        target: "/var/www/html/downloads/linux"
#        strip_components: 3
      
  compile-android:
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
      
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # GraalVM version. Default: latest
        graalvm: '22.0.0.3-Final'
        # Java version. Since GraalVM 22, either java11 or java17, before GraalVM 22, empty. Default: java17
        jdk: 'java17'
      
    - name: Install missing packages
      run: sudo apt-get install libgtk-3-dev libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev
      
    - name: Compile
      run:  locale ; mvn -U -s settings.xml -Pandroid clean gluonfx:compile
      env:
        LANG: "de_DE.UTF-8"

    - name: Link
      run:  mvn -Pandroid gluonfx:link
        
    - name: Show result
      run: ls target/gluonfx

    - name: Package
      run:  mvn -Pandroid gluonfx:package
        
    - name: Show result
      run: |
         ls target/gluonfx/aarch64-android/gvm 
         find target/gluonfx/aarch64-android/gensrc/android 
         cat target/gluonfx/aarch64-android/gensrc/android/AndroidManifest.xml
         zip -r android-gensrc.zip target/gluonfx/aarch64-android/gensrc/android

    - name: Upload Generated sources
      uses: actions/upload-artifact@v1
      with:
        name: android-gensrc.zip
        path: android-gensrc.zip

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: ComLink6-de.apk
        path: target/gluonfx/aarch64-android/gvm/ComLink6.apk
        
#    - name: Upload
#      uses: appleboy/scp-action@master
#      with:
#        host: euve265084.serverprofi24.de
#        username: bitbucket
#        password: Oop6oi1o
#        source: "target/client/aarch64-android/gvm/*.apk"
#        target: "/var/www/html/downloads/linux"
#        strip_components: 4
      
      