name: Compile Linux Self
on: [push]
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "de_DE.UTF-8"

jobs:
  compile-linux-native:
    runs-on: [self-hosted, Linux]
    steps:
    - name: checkout sources
      uses: actions/checkout@v3
 
#    - uses: actions/cache@v1
#      with:
#        path: ~/.m2/repository
#        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#        restore-keys: |
#          ${{ runner.os }}-maven-    

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        
    - name: Compile
      run:  export LC_ALL=de_DE.UTF-8; export LC_MESSAGES=de_DE.UTF-8; locale ; mvn -U -s settings.xml clean gluonfx:compile -Pdesktop
      env: 
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        LANG: de_DE
        CC: gcc-11
        CXX: g++-11
      
#    - name: Install missing packages
#      run: sudo apt-get install libgtk-3-dev libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev  libpango1.0-dev libxtst-dev

    - name: Link
      run:  mvn gluonfx:link -Pdesktop
        
    - name: Show result
      run: ls -l target/gluonfx/x86_64-linux

    - name: Create Native Installer
      run:  mvn gluonfx:package -Pdesktop

#    - name: Logs
#      if: always()      
#      run: cat target/gluonfx/x86_64-linux/gvm/log/client-debug0.log
        
    - name: Show result
      run: ls -l target/gluonfx/x86_64-linux 
        
    - name: Prepare staging
      run: |
        mkdir -p staging ; 
        cp target/gluonfx/x86_64-linux/CommLink6 staging/commlink6-${{ env.RELEASE_VERSION }} ;
        chmod 755 staging/*  ;
        ls staging
      
    - name: Upload
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        verbose: true
        local: staging/commlink6-${{ env.RELEASE_VERSION }}
        remote: /var/www/html/commlink6-builds/linux/CommLink6-${{env.RELEASE_VERSION}}
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}

  compile-linux-jre:
    runs-on: [self-hosted, Linux]
    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        
    - name: Compile update artifact
      run: mvn package
    
    - name: Upload update artifact
      continue-on-error: false
      uses: garygrossgarten/github-action-scp@release
      with:
        verbose: true
        local: target/commlink6-${{ env.RELEASE_VERSION }}-jar-with-dependencies.jar
        remote: /var/www/html/commlink6-updates/linux/commLink6-${{env.RELEASE_VERSION}}.jar
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}

    - name: JPackage
      run:  mvn jpackage:jpackage
        
    - name: Show result
      run: ls target/jpackage
      
    - name: Upload JRE RPM
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        verbose: true
        local: target/jpackage/commlink6-${{ env.RELEASE_VERSION }}-1.x86_64.rpm
        remote: /var/www/html/commlink6-builds/linux/CommLink6-jre-${{env.RELEASE_VERSION}}.rpm
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}
      
    - name: Upload JRE DEB
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        verbose: true
        local: target/jpackage/commlink6-${{ env.RELEASE_VERSION }}-1_amd64.deb
        remote: /var/www/html/commlink6-builds/linux/CommLink6-jre-${{env.RELEASE_VERSION}}.deb
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}
    