name: Compile OS X
on: [push]
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "de_DE.UTF-8"

jobs:
   compile-jpackage:
     runs-on: macos-latest
     steps:
     - name: checkout sources
       uses: actions/checkout@v4

     - uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: '21'

     - name: Set Release version env variable
       run: |
         echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

     - name: Compile 
       run:  export LC_ALL=en_EN.UTF-8; export LC_MESSAGES=en_EN.UTF-8; locale ; mvn -U -s settings.xml clean package  -Pdesktop
       env:
         LANG: en_EN
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: JPackage
       run:   mvn -s settings.xml jpackage:jpackage@osx
       env:
         LANG: en_EN
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
     - name: Show result JPackage
       continue-on-error: true
       run: ls -l target/jpackage
       
     - name: Try scp
       continue-on-error: true
       run: scp -v ; ls

     - name: Archive production artifacts PKG
       uses: actions/upload-artifact@v4
       with:
         name: Commlink6-${{env.RELEASE_VERSION}}.pkg
         path: target/jpackage/Commlink6-${{env.RELEASE_VERSION}}.pkg

     - name: Archive production artifacts DMG
       uses: actions/upload-artifact@v4
       with:
         name: Commlink6-${{env.RELEASE_VERSION}}.dmg
         path: target/jpackage/Commlink6-${{env.RELEASE_VERSION}}.dmg

     - name: Set up SSH
       uses: webfactory/ssh-agent@v0.9.0
       with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                                 
     - name: Upload
       run: scp -o ConnectTimeout=30 target/jpackage/Commlink6-${{env.RELEASE_VERSION}}.dmg ghcommlink@eden.rpgframework.de
       
     - name: Upload
       continue-on-error: true
       uses: garygrossgarten/github-action-scp@release
       with:
         verbose: true
         local: target/jpackage/Commlink6-${{env.RELEASE_VERSION}}.dmg
         remote: /var/www/html/commlink6-builds/osx/CommLink6-Interpreted-${{env.RELEASE_VERSION}}.dmg
         host: eden.rpgframework.de
         username: ghcommlink
         password: ${{ secrets.DEPLOY_PASSWORD }}

   compile-osx-native:
    runs-on: macos-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v4

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.7
    - name: Debug Maven
      run: mvn -version

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Compile
      run:  export LC_ALL=en_EN.UTF-8; export LC_MESSAGES=en_EN.UTF-8; locale ; mvn -U -s settings.xml clean gluonfx:compile -Pdesktop-binary
      env:
        LANG: en_EN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CC: gcc-11
        CXX: g++-11

    - name: Link
      run:  mvn gluonfx:link -Pdesktop-binary
        
    - name: Show result
      run: ls -l target/gluonfx/x86_64-darwin

    - name: Package
      run:  mvn gluonfx:package -Pdesktop-binary
        
    - name: Show result
      continue-on-error: true
      run: ls -l target/gluonfx/x86_64-darwin ; find target/gluonfx/x86_64-darwin

    - name: Logs
      continue-on-error: true
      if: always()      
      run: find target/gluonfx/x86_64-darwin/gensrc/darwin ; cat target/gluonfx/x86_64-darwin/gvm/log/client-debug0.log

    - name: zip APP bundle
      continue-on-error: true
      run: cd target/gluonfx/x86_64-darwin ; zip -r CommLink6.app.zip  CommLink6.app
        
    - name: Prepare staging
      continue-on-error: true
      run: |
        mkdir staging ; 
        cp target/gluonfx/x86_64-darwin/CommLink6 staging/Commlink6-${{ env.RELEASE_VERSION }}-binary ; 
        cp -r target/gluonfx/x86_64-darwin/CommLink6.app staging/Commlink6-${{ env.RELEASE_VERSION }}.app ; 
        cp -r target/gluonfx/x86_64-darwin/CommLink6.app.zip staging/Commlink6-${{ env.RELEASE_VERSION }}.app.zip ; 
        chmod 755 staging/*
        
    - name: Show result
      run: ls target/gluonfx/x86_64-darwin ; find staging

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Commlink6-${{env.RELEASE_VERSION}}
        path: staging/Commlink6-${{ env.RELEASE_VERSION }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Commlink6-${{env.RELEASE_VERSION}}.app.zip
        path: staging/Commlink6-${{ env.RELEASE_VERSION }}.app.zip
      
    - name: Upload
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        verbose: true
        local: staging/Commlink6-${{ env.RELEASE_VERSION }}
        remote: /var/www/html/commlink6-builds/osx/CommLink6-${{env.RELEASE_VERSION}}
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}
      
    - name: Upload APP bundle
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        local: staging/Commlink6-${{ env.RELEASE_VERSION }}.app.zip
        remote: /var/www/html/commlink6-builds/osx/CommLink6-${{env.RELEASE_VERSION}}.app.zip
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}


