name: Compile OS X
on: [push]
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "de_DE.UTF-8"

jobs:

  compile-jpackage:
    runs-on: macos-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v3

    - name: Debug Maven
      run: mvn -version

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Compile 
      run:  export LC_ALL=en_EN.UTF-8; export LC_MESSAGES=en_EN.UTF-8; locale ; mvn -U -s settings.xml clean package  -Pdesktop
      env: 
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        LANG: en_EN

    - name: JPackage
      run:   mvn jpackage:jpackage@osx
      env: 
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        LANG: en_EN
        
    - name: Show result JPackage
      continue-on-error: true
      run: find target
        
    - name: Show result
      continue-on-error: true
      run: find target/tmp
