name: Compile OS X
#on: [push]
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "de_DE.UTF-8"

jobs:
  compile-osx:
    runs-on: macos-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v3
 
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.7

    - name: Debug Maven
      run: mvn -version

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Compile
      run:  export LC_ALL=en_EN.UTF-8; export LC_MESSAGES=en_EN.UTF-8; locale ; mvn -U -s settings.xml clean gluonfx:compile -Pdesktop
      env: 
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        LANG: en_EN
        CC: gcc-11
        CXX: g++-11

    - name: Link
      run:  mvn gluonfx:link -Pdesktop-binary
        
    - name: Show result
      run: ls -l target/gluonfx/x86_64-darwin

    - name: Package
      run:  mvn gluonfx:package -Pdesktop-binary
        
    - name: Show result
      continue-on-error: true
      run: ls -l target/gluonfx/x86_64-darwin ; find target/gluonfx/x86_64-darwin

    - name: Logs
      continue-on-error: true
      if: always()      
      run: find target/gluonfx/x86_64-darwin/gensrc/darwin ; cat target/gluonfx/x86_64-darwin/gvm/log/client-debug0.log

    - name: zip APP bundle
      continue-on-error: true
      run: cd target/gluonfx/x86_64-darwin ; zip -r CommLink6.app.zip  CommLink6.app
        
    - name: Prepare staging
      continue-on-error: true
      run: |
        mkdir staging ; 
        cp target/gluonfx/x86_64-darwin/CommLink6 staging/Commlink6-${{ env.RELEASE_VERSION }} ; 
        cp -r target/gluonfx/x86_64-darwin/CommLink6.app staging/Commlink6-${{ env.RELEASE_VERSION }}.app ; 
        cp -r target/gluonfx/x86_64-darwin/CommLink6.app.zip staging/Commlink6-${{ env.RELEASE_VERSION }}.app.zip ; 
        chmod 755 staging/*
        
    - name: Show result
      run: ls target/gluonfx/x86_64-darwin ; find staging
      
    - name: Upload
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        verbose: true
        local: staging/Commlink6-${{ env.RELEASE_VERSION }}
        remote: /var/www/html/commlink6-builds/osx/CommLink6-${{env.RELEASE_VERSION}}
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}
      
    - name: Upload
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        verbose: true
        local: staging/Commlink6-${{ env.RELEASE_VERSION }}.app.zip
        remote: /var/www/html/commlink6-builds/osx/CommLink6-${{env.RELEASE_VERSION}}.app.zip
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}

    - name: JPackage
      continue-on-error: true
      run: mvn jpackage:jpackage@osx 
        
    - name: Show result JPackage
      run: ls -l target/jpackage
        
    - name: Show result
      run: find target/tmp
