name: Compile Windows
on: [push]
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "de_DE.UTF-8"

jobs:
  compile-windows:
    runs-on: windows-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
 
    # Setup the Windows build environment
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Visual Studio shell
      uses: egor-tensin/vs-shell@v1

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile
      run:  mvn -U -s settings.xml clean gluonfx:compile
      env: 
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        LANG: de_DE

    - name: Link
      run:  mvn gluonfx:link
        
    - name: Show result
      run: ls target/gluonfx

    - name: Package
      run:  mvn gluonfx:package
        
    - name: Show result
      run: ls target/gluonfx/x86_64-windows

    - name: Logs
      if: always()      
      run: cat target\gluonfx\x86_64-windows/gvm/log/client-debug0.log

    - name: Upload Windows binary
      uses: actions/upload-artifact@v1
      with:
        name: ComLink6-Windows
        path: target/gluonfx/x86_64-windows/ComLink6.exe

    - name: Upload Windows MSI
      uses: actions/upload-artifact@v1
      with:
        name: ComLink6-Windows
        path: target/gluonfx/x86_64-windows/ComLink6-1.0.msi

#    - name: Upload 
#      uses: appleboy/scp-action@master
#      with:
#        host: euve265084.serverprofi24.de
#        username: bitbucket
#        password: Oop6oi1o
#        source: "target/client/x86_64-linux/Mondtor"
#        target: "/var/www/html/downloads/linux"
#        strip_components: 3
       