name: Compile Windows Cloud
#on: [push]
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "de_DE.UTF-8"

jobs:
  compile-windows:
    runs-on: windows-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v3
 
    # Setup the Windows build environment
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Visual Studio shell
      uses: egor-tensin/vs-shell@v2

    - name: Get version (bash)
      continue-on-error: true
      shell: bash -l {0}
      run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: setup-graalvm-ce
      uses: taranion/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.7

    - name: Debug Maven
      run: mvn -version

    - name: Compile
      run:  mvn -U -s settings.xml clean gluonfx:compile -Pdesktop-binary
      env: 
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        LANG: de_DE

    - name: Link
      run:  mvn -U -s settings.xml gluonfx:link -Pdesktop-binary
        
    - name: Show result
      run: ls target/gluonfx/x86_64-windows

    - name: Package
      run:  mvn gluonfx:package -Pdesktop
        
    - name: Show result Native
      run: ls target/gluonfx/x86_64-windows

    - name: Prepare staging
      continue-on-error: true
      run: |
        mkdir Staging ; 
        cp target/gluonfx/x86_64-windows/CommLink6.exe Staging/Commlink6_Native_${{ env.RELEASE_VERSION }}.exe; 
        cp target/gluonfx/x86_64-windows/CommLink6-*msi Staging/Commlink6_Native_${{ env.RELEASE_VERSION }}.msi ; 
        ls Staging

    - name: Logs
      if: always()      
      run: cat target\gluonfx\x86_64-windows/gvm/log/client-debug0.log

    - name: Show created WIX config file
      run: cat target\gluonfx\x86_64-windows\gvm\tmp\tmpMSI\config\main.wxs 

#    - name: Upload Windows binary
#      continue-on-error: true
#      uses: actions/upload-artifact@v1
#      with:
#        name: CommLink6-Windows-Executable-${{ env.RELEASE_VERSION }}
#        path: target/gluonfx/x86_64-windows/CommLink6.exe
#
#    - name: Upload Windows MSI
#      continue-on-error: true
#      uses: actions/upload-artifact@v1
#      with:
#        name: CommLink6-Windows-Installer-${{ env.RELEASE_VERSION }}
#        path: target/gluonfx/x86_64-windows/Commlink6-${{ env.RELEASE_VERSION }}.msi
      
    - name: Deploy Native EXE
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "Staging\\Commlink6_Native_${{ env.RELEASE_VERSION }}.exe"
        remote: /var/www/html/commlink6-builds/win/CommLink6-Binary-${{env.RELEASE_VERSION}}.exe
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}
      
    - name: Deploy MSI
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "Staging\\Commlink6_Native_${{ env.RELEASE_VERSION }}.msi"
        remote: /var/www/html/commlink6-builds/win/Commlink6-Binary-Installer-${{env.RELEASE_VERSION}}.msi
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}

  compile-windows-jre:
    runs-on: windows-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
 
    # Setup the Windows build environment
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Visual Studio shell
      uses: egor-tensin/vs-shell@v2

    - name: Get version (bash)
      continue-on-error: true
      shell: bash -l {0}
      run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: setup-graalvm-ce
      uses: taranion/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile
      run:  mvn  -U -s settings.xml clean package jpackage:jpackage@win -Pdesktop
      env: 
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}
        LANG: de_DE
        
    - name: Show result JPackage
      run: ls -l target/jpackage

    - name: Prepare staging 2
      continue-on-error: true
      run: mkdir Staging ; cp target/jpackage/Commlink6-*.msi Staging/
        
    - name: Show Staging content
      run: ls -l Staging
      
    - name: Deploy MSI
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "target\\jpackage\\Commlink6-${{env.RELEASE_VERSION}}.msi"
        remote: /var/www/html/commlink6-builds/win/CommLink6-Interpreted-Installer-${{env.RELEASE_VERSION}}.msi
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}
       